# Generated by Django 5.0.2 on 2024-03-26 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_grades_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='bulk',
        ),
    ]
