# Generated by Django 5.0.6 on 2024-05-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_grades_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='competence',
        ),
        migrations.AddField(
            model_name='activity',
            name='capacity',
            field=models.ManyToManyField(to='my_grades_api.capacity'),
        ),
        migrations.AddField(
            model_name='activity',
            name='competence',
            field=models.ManyToManyField(to='my_grades_api.competence'),
        ),
    ]
