# Generated by Django 5.0.2 on 2024-02-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_grades_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='califaction',
            field=models.CharField(blank=True, choices=[('AD', 'AD'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=2, null=True),
        ),
    ]
