# Generated by Django 5.0.1 on 2024-01-22 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_grades_api', '0002_assignment_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='my_grades_api.student')),
            ],
        ),
    ]
