# Generated by Django 5.0.2 on 2024-02-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_grades_api', '0002_assignment_califaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_type',
            field=models.CharField(choices=[('P', 'Project'), ('Q', 'Quizz'), ('T', 'Test'), ('H', 'Homework')], max_length=1),
        ),
    ]
