# Generated by Django 5.0.6 on 2024-05-14 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_grades_api', '0003_activity_my_choices_alter_activity_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='my_choices',
        ),
    ]
