# Generated by Django 5.0.2 on 2024-02-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_grades_api', '0003_alter_assignment_assignment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='bulk',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clase',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
