# Generated by Django 5.0.1 on 2024-01-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_grades_api', '0003_atendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendance',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
