# Generated by Django 5.0.2 on 2024-03-27 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_grades_api', '0004_instructor_is_instructor_student_is_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='is_instructor',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='is_tutor',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
