# Generated by Django 5.0.2 on 2024-02-27 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_grades_api', '0004_clase_bulk_alter_clase_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='description',
        ),
    ]
