# Generated by Django 5.0.2 on 2024-03-28 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_grades_api', '0005_remove_instructor_is_instructor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='instructor',
        ),
    ]
