# Generated by Django 5.0.6 on 2024-05-14 17:15

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_grades_api', '0005_activity_my_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='competence',
        ),
        migrations.AddField(
            model_name='activity',
            name='competences',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Construye su identidad.'), ('2', 'Convive y participa democráticamente en la búsqueda del bien común.'), ('3', 'Construye interpretaciones históricas.'), ('4', 'Gestiona responsablemente el espacio y el ambiente.')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
