# Generated by Django 5.0.6 on 2024-05-14 17:36

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_grades_api', '0006_remove_activity_capacity_remove_activity_competence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='competences',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'Item title 1.1'), ('item_key2', 'Item title 1.2'), ('item_key3', 'Item title 1.3'), ('item_key4', 'Item title 1.4'), ('item_key5', 'Item title 1.5')], max_length=20),
        ),
    ]
