# Generated by Django 5.0.2 on 2024-04-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_grades_api', '0006_remove_activity_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendance',
            name='created_by',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
