# Generated by Django 5.0.6 on 2024-05-14 17:45

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_grades_api', '0007_alter_activity_competences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='my_choices',
        ),
        migrations.AlterField(
            model_name='activity',
            name='competences',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '11')], max_length=20),
        ),
    ]
