# Generated by Django 5.0.2 on 2024-03-01 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_grades_api', '0007_alter_assignment_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='my_grades_api.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='my_grades_api.school'),
            preserve_default=False,
        ),
    ]
