# Generated by Django 5.0.2 on 2024-04-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_grades_api', '0008_activity_description_tutor_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
