# Generated by Django 5.0.2 on 2024-04-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_grades_api', '0009_alter_tutor_first_name_alter_tutor_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
