# Generated by Django 5.0.6 on 2024-05-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_grades_api', '0009_activity_capacities_alter_activity_competences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='capacities',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='activity',
            name='competences',
            field=models.CharField(max_length=255),
        ),
    ]
