# Generated by Django 5.0.2 on 2024-03-15 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_grades_api', '0009_remove_assignment_assignment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competence',
            name='assignature',
        ),
    ]
