# Generated by Django 5.0.2 on 2024-03-15 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_grades_api', '0010_remove_competence_assignature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='clase',
        ),
    ]
