# Generated by Django 5.0.2 on 2024-04-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_grades_api', '0010_alter_instructor_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='student',
        ),
        migrations.AddField(
            model_name='tutor',
            name='student',
            field=models.ManyToManyField(related_name='tutors', to='my_grades_api.student'),
        ),
    ]
