# Generated by Django 5.0.2 on 2024-04-03 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_grades_api', '0011_remove_tutor_student_tutor_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='student',
            new_name='students',
        ),
    ]
