# Generated by Django 5.0.2 on 2024-03-15 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_grades_api', '0011_remove_assignment_clase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='califaction',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='student',
        ),
    ]
