# Generated by Django 5.0.6 on 2024-05-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_grades_api', '0011_quartergrade_conclusion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='quarter',
            field=models.CharField(choices=[('Q1', 'First Quarter'), ('Q2', 'Second Quarter'), ('Q3', 'Third Quarter'), ('Q4', 'Fourth Quarter')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
