# Generated by Django 5.0.2 on 2024-03-15 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_grades_api', '0012_remove_assignment_califaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calification', models.CharField(choices=[('AD', 'AD'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=2)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade', to='my_grades_api.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade', to='my_grades_api.student')),
            ],
        ),
    ]
