# Generated by Django 5.0.6 on 2024-05-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_grades_api', '0012_participation_quarter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='competence',
        ),
        migrations.AddField(
            model_name='participation',
            name='capacities',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participation',
            name='competences',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
