# Generated by Django 5.0.6 on 2024-05-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_grades_api', '0013_remove_participation_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='created_at',
            field=models.DateField(),
        ),
    ]
