# Generated by Django 5.0.2 on 2024-04-05 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_grades_api', '0013_activity_is_participation_grade_observations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='is_participation',
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calification', models.CharField(choices=[('AD', 'AD'), ('A', 'A'), ('B', 'B'), ('C', 'C')], default='NA', max_length=2)),
                ('observations', models.TextField(blank=True, null=True)),
                ('assignature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_grades_api.assignature')),
                ('capacity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='my_grades_api.capacity')),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='my_grades_api.competence')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='my_grades_api.student')),
            ],
        ),
    ]
