# Generated by Django 5.0.2 on 2024-03-17 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_grades_api', '0013_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendance',
            name='status',
        ),
        migrations.AddField(
            model_name='atendance',
            name='hour',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='my_grades_api.assignment'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='calification',
            field=models.CharField(choices=[('NA', 'NA'), ('AD', 'AD'), ('A', 'A'), ('B', 'B'), ('C', 'C')], default='NA', max_length=2),
        ),
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='my_grades_api.student'),
        ),
    ]
