# Generated by Django 5.0.6 on 2024-06-10 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_grades_api', '0014_alter_participation_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignature',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='my_grades_api.school'),
            preserve_default=False,
        ),
    ]
