# Generated by Django 5.0.2 on 2024-04-06 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_grades_api', '0014_remove_activity_is_participation_participation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='capacity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='my_grades_api.capacity'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='competence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='my_grades_api.competence'),
        ),
    ]
