# Generated by Django 5.0.2 on 2024-03-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_grades_api', '0014_remove_atendance_status_atendance_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendance',
            name='status',
            field=models.CharField(blank=True, choices=[('L', 'Late'), ('N', 'Not Attended')], max_length=1),
        ),
    ]
