# Generated by Django 5.0.2 on 2024-04-06 12:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_grades_api', '0015_alter_participation_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
