# Generated by Django 5.0.2 on 2024-03-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_grades_api', '0015_atendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atendance',
            name='status',
            field=models.CharField(choices=[('L', 'Late'), ('N', 'Not Attended')], max_length=1),
        ),
    ]
