# Generated by Django 5.0.6 on 2024-06-15 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_grades_api', '0016_annunciationimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='annunciation',
            name='quarter',
            field=models.CharField(blank=True, choices=[('Q1', 'First Quarter'), ('Q2', 'Second Quarter'), ('Q3', 'Third Quarter'), ('Q4', 'Fourth Quarter')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='annunciationimages',
            name='annunciation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annunciation_imgs', to='my_grades_api.annunciation'),
        ),
    ]
