# Generated by Django 5.0.2 on 2024-03-25 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_grades_api', '0016_student_first_name_student_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='assignature',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='my_grades_api.assignature'),
            preserve_default=False,
        ),
    ]
