# Generated by Django 5.0.2 on 2024-05-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_grades_api', '0018_remove_category_instructor_category_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='quarter',
            field=models.CharField(choices=[('Q1', 'First Quarter'), ('Q2', 'Second Quarter'), ('Q3', 'Third Quarter'), ('Q4', 'Fourth Quarter')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
