# Generated by Django 5.0.2 on 2024-05-08 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_grades_api', '0020_annunciation'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarterGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calification', models.CharField(choices=[('AD', 'AD'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=2)),
                ('quarter', models.CharField(choices=[('Q1', 'First Quarter'), ('Q2', 'Second Quarter'), ('Q3', 'Third Quarter'), ('Q4', 'Fourth Quarter')], max_length=2)),
                ('assignature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_grades_api.assignature')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='averages', to='my_grades_api.student')),
            ],
        ),
    ]
