# Generated by Django 5.0.2 on 2024-05-08 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_grades_api', '0021_quartergrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='quartergrade',
            name='competence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='my_grades_api.competence'),
            preserve_default=False,
        ),
    ]
