# Generated by Django 5.0.2 on 2024-03-27 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
