# Generated by Django 5.0.6 on 2024-05-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.CharField(blank=True, choices=[('S', 'Student'), ('T', 'Tutor'), ('I', 'Instructor'), ('A', 'Auxiliar')], max_length=1, null=True),
        ),
    ]
