# Generated by Django 5.0.2 on 2024-04-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.CharField(choices=[('S', 'Student'), ('T', 'Tutor'), ('I', 'Instructor'), ('A', 'Auxiliar')], max_length=1),
        ),
    ]
